name: painn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipython
  - jedi
  - matplotlib-inline
  - pip
  - prompt-toolkit
  - pygments
  - readline
  - setuptools
  - sqlite
  - tk
  - traitlets
  - xz
  - zlib
  - tzdata
  - ncurses
  - libffi
  - openssl
  - six
  - wheel
  - bzip2
  - pexpect
  - decorator
  - parso
  - stack_data
  - wcwidth
  - asttokens
  - executing
  - pure_eval
  - pip:
      - aiohappyeyeballs>=2.4.3
      - aiohttp>=3.10.10
      - aiosignal>=1.3.1
      - attrs>=24.2.0
      - certifi>=2024.8.30
      - charset-normalizer>=3.4.0
      - filelock>=3.16.1
      - frozenlist>=1.5.0
      - fsspec>=2024.10.0
      - idna>=3.10
      - jinja2>=3.1.4
      - lightning>=2.4.0
      - lightning-utilities>=0.11.8
      - markupsafe>=3.0.2
      - mpmath>=1.3.0
      - multidict>=6.1.0
      - networkx>=3.4.2
      - numpy>=1.26.4
      - packaging>=24.1
      - propcache>=0.2.0
      - psutil>=6.1.0
      - pyparsing>=3.2.0
      - pytorch-lightning>=2.4.0
      - pyyaml>=6.0.2
      - requests>=2.32.3
      - sympy>=1.13.1
      - torch>=2.5.1
      - torch-geometric>=2.6.1
      - torchmetrics>=1.5.1
      - tqdm>=4.66.6
      - triton>=3.1.0
      - typing-extensions>=4.12.2
      - urllib3>=2.2.3
      - yarl>=1.17.1
